#!/bin/sh

set -e

PYTHON="python3"

rm -f test.pub test.prv null.sig
$PYTHON -m pyhsslms.hsslms genkey test $*
echo "## $*"
echo "\`\`\`\`"
$PYTHON -m pyhsslms.hsslms showprv test
$PYTHON -m pyhsslms.hsslms showpub test
echo "\`\`\`\`"
$PYTHON -m pyhsslms.hsslms sign test null
echo "\`\`\`\`"
ls -l test.*
ls -l null.sig
echo "\`\`\`\`"
$PYTHON -m pyhsslms.hsslms verify test null